Backport of 12793 to branches/5.0.x: ------------------------------------------------------------------------ r12793 | dstrubbe | 2015-01-30 16:59:01 -0500 (Fri, 30 Jan 2015) | 16 lines
Fixing these warnings from clang C compiler, due to r12714:
{{{
oct_f.c:179:6: warning: implicit declaration of function 'dirname' is invalid in C99 [-Wimplicit-function-declaration]
  dn=dirname(fn);
     ^
oct_f.c:179:5: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int';
  dn=dirname(fn);
    ^~~~~~~~~~~~
oct_f.c:194:6: warning: implicit declaration of function 'basename' is invalid in C99 [-Wimplicit-function-declaration]
  bn=basename(fn);
     ^
oct_f.c:194:5: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int';
  bn=basename(fn);
    ^~~~~~~~~~~~~
}}}

------------------------------------------------------------------------